### ISSUE TITLE
Config not initialized

### ISSUE THREAD

**Issue by Tllokn** [cbenning/fussel#118]
when run 'generate.sh' meet problem
AttributeError: 'Config' object has no attribute 'overwrite'

I guess it is because inside config.py instance() method:
    @classmethod
    def instance(cls):
        if cls._instance is None:
            print('Creating new instance')
            cls._instance = cls.__new__(cls)
            # Put any initialization here.
        return cls._instance

there is no initilization automatically call?

**Comment by Tllokn** [comment]
Sure, here is the stacktrace

```
Generating site from /pathhide/PhotoGallery/photos
Importing /pathhide/PhotoGallery/photos/Tianjin
Detecting Faces...
Importing /pathhide/PhotoGallery/photos/Tianjin/1 as tianjin > 1 (tianjin-1)
 --> Processing /pathhide/PhotoGallery/photos/Tianjin/1/787A6964.JPG...
 --> Processing /pathhide/PhotoGallery/photos/Tianjin/1/787A7059.JPG...
Creating new instance
Creating new instance
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/pathhide/PhotoGallery/fussel-main/fussel/generator/generate.py", line 266, in _process_photo
    return (photo_file, Photo.process_photo(external_path, photo_file, filename, unique_slug, album_folder, _process_photo.people_q))
  File "/pathhide/PhotoGallery/fussel-main/fussel/generator/generate.py", line 193, in process_photo
    if Config.instance().overwrite or not os.path.exists(new_original_photo):
AttributeError: 'Config' object has no attribute 'overwrite'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/pathhide/PhotoGallery/fussel-main/fussel/./fussel.py", line 83, in <module>
    main()
  File "/pathhide/PhotoGallery/fussel-main/fussel/./fussel.py", line 44, in main
    generator.generate()
  File "/pathhide/PhotoGallery/fussel-main/fussel/generator/generate.py", line 442, in generate
    Albums.instance().process_path(Config.instance().input_photos_dir,
  File "/pathhide/PhotoGallery/fussel-main/fussel/generator/generate.py", line 314, in process_path
    self.process_album_path(
  File "/pathhide/PhotoGallery/fussel-main/fussel/generator/generate.py", line 388, in process_album_path
    self.process_album_path(
  File "/pathhide/PhotoGallery/fussel-main/fussel/generator/generate.py", line 359, in process_album_path
    results = P.map(_process_photo, jobs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
AttributeError: 'Config' object has no attribute 'overwrite'
```

**Comment by dejl** [comment]
I get the same.

**Comment by misilot** [comment]
Also getting the same, has anyone found a solution?

**Comment by mxz94** [comment]
> 同样得到同样的问题，有人找到解决方案了吗？

_process_photo  函数是在线程里面执行，无法获取外面的Config.instance()。传进去就可以了
![image](https://github.com/user-attachments/assets/3ef2ae46-c084-471d-b0be-171035ca7ccd)

**Comment by cbenning** [comment]
Can you try the new `2.1.0` version and let me know if its fixed? I believe it should be.

**Comment by spyros1973** [comment]
Running v2.1, I still get this error with the exact same tracelog. Running on Windows.

If I dump the Config value like:
```
     print ('Requesting config and getting ' + str(Config.instance().__dict__))
        # Only copy if overwrite explicitly asked for or if doesn't exist
        if Config.instance().overwrite or not os.path.exists(new_original_photo):
            print(f' ----> Copying to [magenta]{new_original_photo}[/magenta]')
            shutil.copyfile(photo, new_original_photo)
```

My printout is:
Requesting config and getting {}
