### ISSUE TITLE
try, except PIL.UnidentifiedImageError in generate_site.sh

### ISSUE THREAD

**Issue by miek770** [cbenning/fussel#21]
I've just received this error:

```
 --> Processing /mnt/Photos/170221 - Grand-père Jean-Marc/108.jpg... 
 ----> Copying to '/home/fussel/app/fussel/web/public/static/_gallery/albums/170221 - Grand-père Jean-Marc/original_108.jpg'
Traceback (most recent call last):
  File "./fussel.py", line 74, in <module>
    generator.generate_site(output_photos_path, output_data_path, http_root)
  File "/home/fussel/app/fussel/generator/generate.py", line 333, in generate_site
    self.process_album(album_dir, album_name, output_albums_photos_path, external_root)
  File "/home/fussel/app/fussel/generator/generate.py", line 297, in process_album
    faces, photo_data = self.process_photo(external_path, photo_file, album_folder)
  File "/home/fussel/app/fussel/generator/generate.py", line 38, in process_photo
    with Image.open(new_original_photo) as im:
  File "/home/fussel/app/lib/python3.6/site-packages/PIL/Image.py", line 2896, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file '/home/fussel/app/fussel/web/public/static/_gallery/albums/170221 - Grand-père Jean-Marc/original_108.jpg'
```

I'll check if the extension doesn't match the image type, but `generate_site.sh` should try/except and watch for `PIL.UnidentifiedImageError`, and issue a warning and skip the file if it happens.

---

Yep that's actually a video, my library is a bit messy :(

```
(app) fussel@odroid:~/app/fussel$ file '/home/fussel/app/fussel/web/public/static/_gallery/albums/170221 - Grand-père Jean-Marc/original_108.jpg'
/home/fussel/app/fussel/web/public/static/_gallery/albums/170221 - Grand-père Jean-Marc/original_108.jpg: ISO Media, Apple iTunes Video (.M4V) Video
```

**Comment by cbenning** [comment]
In the next release, you will see:

``` > Importing album .../demo_photos/not_photo as 'not_photo'
 --> Processing .../demo_photos/not_photo/discord-0.0.10.jpg... 
Skipping processing of image file .../demo_photos/not_photo/discord-0.0.10.jpg. Reason: cannot identify image file '.../fussel/web/public/static/_gallery/albums/not_photo/original_discord-0.0.10.jpg'```

Then it should continue on.
